ergast.url: http://ergast.com/api/f1

logging:
  level:
    ROOT: INFO

spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: vilela
    driverClassName: org.postgresql.Driver

feign:
  client:
    config:
      default:
        loggerLevel: basic
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000
      circuitBreaker:
        requestVolumeThreshold: 30
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50